[package]
name = "nasapi"
version = "0.1.0"
authors = ["Tyler Wilcock <twilcock@widen.com>"]

[dependencies]
reqwest = "0.8.6"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.22"
failure = "0.1.1"
url = "1.7.1"
